name: Flutter CI Full

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - deve1

jobs:
  flutter-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          cache: true

      - name: Cache Pub Packages
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Flutter Doctor
        run: flutter doctor

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Flutter Analyze
        run: flutter analyze

      - name: Run Tests
        run: flutter test --coverage

      - name: Check Formatting
        run: dart format --set-exit-if-changed .

      - name: Clean build cache
        run: flutter clean

      - name: Build APK
        run: flutter build apk --release
